# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b9226419ac56ff34385421dec8bc81961c55bdc67dde48e4c3716eebc83a9c160509aa91bfebdcdf64befe7483868989b6b7188ca93fb93ce48da113b838878

test:
  secret_key_base: 559a8340c36b491f4a1e419b205b77dc91f71b388ae127ff5b7956d6bd0a73b4eb2aaefcd42ae1a4959e968b293d11fcca0d341dae20182d5e9b401e256297ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
